% Mon 22 Jan 16:56:18 CET 2018
function h = plot(obj,val)
	if (0)
		X = obj.cX1;
		Y = obj.cX2;
		h = surface(X,Y,double(val(:,:,id)).');
	else
		% TODO patch should be generated by obj2
		X = obj.XX1;
		Y = obj.XX2;
		% top left
		X_(:,1) = flat(X(1:end-1,1:end-1));
		Y_(:,1) = flat(Y(1:end-1,1:end-1));
		%  top right
		X_(:,2) = flat(X(1:end-1,2:end));
		Y_(:,2) = flat(Y(1:end-1,2:end));
		% bottom right
		X_(:,3) = flat(X(2:end,2:end));
		Y_(:,3) = flat(Y(2:end,2:end));
		%  bottom left
		X_(:,4) = flat(X(2:end,1:end-1));
		Y_(:,4) = flat(Y(2:end,1:end-1));
		Z   = flat(val);
		fdx = isfinite(Z);
		%h = patch(X_(fdx,:),Y_(fdx,:),Z(fdx));
		h= patch(X_(fdx,:)',Y_(fdx,:)',0.*Y_(fdx,:)',Z(fdx));
	end
	%h=pcolor(X,Y,val(:,:,id).');
	h.EdgeColor='none';
end

